FORMAT: 1A
HOST: *

# API Consulta Conest
API del sistema de *Consulta Conest*.

# Group Instrumentos
Recursos asociados a los **Instrumentos** de consulta

## Colección de Instrumentos [/instrumentos]
### Listar todos los Instrumentos [GET]
+ Response 200 (application/json)

        [{
          "id": 1, "nombre": "Consulta de teórico-prácticas", "descripcion": "Consulta estudiantil sobre el desempeño docente en materias teórico-prácticas", "created_at": "2014-07-01 09:00:00", "updated_at": "2014-07-01 09:00:00"
        }, {
          "id": 2, "nombre": "Consulta de teóricas", "descripcion": "Consulta estudiantil sobre el desempeño docente en materias teóricas", "created_at": "2014-07-01 09:30:00", "updated_at": "2014-07-01 09:00:00"
        }]

### Crear un Instrumento [POST]
+ Request (application/json)

        { "nombre": "Consulta de Laboratorio", "descripcion": "Consulta estudiantil sobre el desempeño docente en materias de Laboratorios Generales" }

+ Response 201 (application/json)

        { "id": 3, "nombre": "Consulta de Laboratorio", "descripcion": "Consulta estudiantil sobre el desempeño docente en materias cde Laboratorios Generales", "created_at": "2014-07-01 09:30:00", "updated_at": "2014-07-01 09:00:00" }

## Instrumento [/instrumentos/{id}]
Un objeto Instrumento en particular con todos sus detalles

+ Parameters
    + id (required, number, `1`) ... `id` numérico del Instrumento. Tiene un valor de ejemplo.

### Obtener un Instrumento [GET]
+ Response 200 (application/json)

    + Header

            X-My-Header: The Value

    + Body

            { "id": 1, "nombre": "Consulta de teórico prácticas", "descripcion": "Consulta estudiantil sobre el desempeño docente en materias teórico-prácticas", "created_at": "2014-07-01 09:00:00", "updated_at": "2014-07-01 09:00:00" }

### Editar un Instrumento [PUT]
+ Request (application/json)

        { "id": 3, "nombre": "Consulta de Laboratorio", "descripcion": "Consulta estudiantil sobre el desempeño docente en materias de Laboratorios Generales" }

+ Response 201 (application/json)

        { "id": 3, "nombre": "Consulta de Laboratorio", "descripcion": "Consulta estudiantil sobre el desempeño docente en materias cde Laboratorios Generales", "created_at": "2014-07-01 09:30:00", "updated_at": "2014-07-01 09:00:00" }


### Eliminar un Instrumento [DELETE]
+ Response 204












# Group Bloques
Recursos asociados a los **Bloques** que agrupan **conjuntos de preguntas** de un instrumento

## Colección de Bloques de un Instrumento [/instrumentos/{id}/bloques]
### Listar todos los Bloques de un Instrumento [GET]
+ Response 200 (application/json)

        [{
          "id": 1, "nombre": "Sobre el docente", "descripcion": "Aspectos asociados al desempeño del docente", "instrumento_id": 1, "created_at": "2014-07-01 09:00:00", "updated_at": "2014-07-01 09:00:00"
        }, {
          "id": 2, "nombre": "Sobre la asignatura", "descripcion": "Aspectos asociados al contenido y planificación de la asignatura", "instrumento_id": 1, "created_at": "2014-07-01 09:30:00", "updated_at": "2014-07-01 09:00:00"
        }]

### Crear un Bloque [POST]
+ Request (application/json)

        { "nombre": "Sobre el laboratorio", "descripcion": "Aspectos asociados a las actividades docentes de laboratorio", "instrumento_id": 1 }

+ Response 201 (application/json)

        { "id": 3, "nombre": "Sobre el laboratorio", "descripcion": "Aspectos asociados a las actividades docentes de laboratorio", "instrumento": { "id":1, "nombre":"Consulta de teórico-prácticas" }, "created_at": "2014-07-01 09:30:00", "updated_at": "2014-07-01 09:00:00" }

## Bloques [/bloques/{id}]
Un bloque en particular con todos sus detalles

+ Parameters
    + id (required, number, `1`) ... `id` numérico del Bloque. Tiene un valor de ejemplo.

### Obtener un Bloque [GET]
+ Response 200 (application/json)

    + Header

            X-My-Header: The Value

    + Body

            { "id": 1, "nombre": "Sobre el docente", "descripcion": "Aspectos asociados al desempeño del docente", "instrumento": { "id": 1, "nombre": "Consulta de teórico-prácticas" }, "created_at": "2014-07-01 09:00:00",  "updated_at": "2014-07-01 09:00:00" }

### Editar un Bloque [PUT]
+ Request (application/json)

        { "id": 3, "nombre": "Sobre el laboratorio", "descripcion": "Aspectos asociados a las actividades docentes de laboratorio", "instrumento_id": 1 }

+ Response 200 (application/json)

        { "id": 3, "nombre": "Sobre el laboratorio", "descripcion": "Aspectos asociados a las actividades docentes de laboratorio", "instrumento": { "id": 1, "nombre": "Consulta de teórico-prácticas" }, "created_at": "2014-07-01 09:30:00", "updated_at": "2014-07-01 09:00:00" }


### Eliminar un Bloques [DELETE]
+ Response 204









# Group Preguntas
Recursos asociados a las **Preguntas** agrupadas en bloques de un instrumento

## Colección de Preguntas de un Bloque [/bloques/{id}/preguntas]
### Listar todas las Preguntas de un Bloque [GET]
+ Response 200 (application/json)

        [{
          "id": 1, "interrogante": "¿Cómo evalúa la asistencia del docente a clases", "descripcion": "Considere la asistencia puntual y regular a las actividades", "bloque_id": 1, "tipo_pregunta": { "id": 1, "nombre": "Selección Simple" }, "created_at": "2014-07-01 09:00:00", "updated_at": "2014-07-01 09:00:00"
        }, {
          "id": 2, "interrogante": "¿En qué medida se cubrió el contenido planificado", "descripcion": "", "bloque_id": 2, "tipo_pregunta": { "id": 1, "nombre": "Selección Simple" }, "created_at": "2014-07-01 09:30:00", "updated_at": "2014-07-01 09:00:00"
        }]

### Crear una Pregunta [POST]
+ Request (application/json)

        { "interrogante": "¿El docente atendió las dudas presentadas de manera oportuna?", "descripcion": "Dio oportunidad para presentar dudas en cada contenido y supo dar respuesta o material para resolverlas", "bloque_id": 1, "tipo_pregunta_id": 1 }

+ Response 201 (application/json)

        { "id": 3, "interrogante": "¿El docente atendió las dudas presentadas de manera oportuna?", "descripcion": "Dio oportunidad para presentar dudas en cada contenido y supo dar respuesta o material para resolverlas", "bloque_id": 1, "tipo_pregunta": { "id": 1, "nombre": "Selección Simple" }, "created_at": "2014-07-01 09:00:00", "updated_at": "2014-07-01 09:00:00" }


## Preguntas [/preguntas/{id}]
Una pregunta en particular con todos sus detalles

+ Parameters
    + id (required, number, `1`) ... `id` numérico de la pregunta. Tiene un valor de ejemplo.

### Obtener una Pregunta [GET]
+ Response 200 (application/json)

    + Header

            X-My-Header: The Value

    + Body

            { "id": 1, "interrogante": "¿Cómo evalúa la asistencia del docente a clases", "descripcion": "Considere la asistencia puntual y regular a las actividades", bloque: { "id": 1, "nombre": "Sobre el docente", "instrumento": { "id": 1, "nombre": "Consulta de teórico-prácticas" } }, "tipo": { "id": 1, "nombre": "Selección Simple" }, "created_at": "2014-07-01 09:00:00", "updated_at": "2014-07-01 09:00:00" }

### Editar una Pregunta [PUT]
+ Request (application/json)

        { "id": 3, "interrogante": "¿El docente atendió las dudas presentadas de manera oportuna?", "descripcion": "Dio oportunidad para presentar dudas en cada contenido y supo dar respuesta o material para resolverlas", "bloque_id": 1, "tipo_pregunta_id": 1 }

+ Response 200 (application/json)

        { "id": 3, "interrogante": "¿El docente atendió las dudas presentadas de manera oportuna?", "descripcion": "Dio oportunidad para presentar dudas en cada contenido y supo dar respuesta o material para resolverlas", "bloque_id": 1, "tipo": { "id": 1, "nombre": "Selección Simple" }, "created_at": "2014-07-01 09:00:00",  "updated_at": "2014-07-01 09:00:00" }


### Eliminar una Pregunta [DELETE]
+ Response 204


