FORMAT: 1A
HOST: http://www.google.com

# API Consulta Conest
API del sistema de *Consulta Conest*.

# Group Instrumentos
Recursos asociados a los **Instrumentos** de consulta

## Colección de Instrumentos [/instrumentos]
### Listar todos los Instrumentos [GET]
+ Response 200 (application/json)

        [{
          "id": 1, "nombre": "Consulta de teórico-prácticas", "descripcion": "Consulta estudiantil sobre el desempeño docente en materias teórico-prácticas", "created_at": "2014-07-01 09:00:00",  "updated_at": "2014-07-01 09:00:00"
        }, {
          "id": 2, "nombre": "Consulta de teóricas", "descripcion": "Consulta estudiantil sobre el desempeño docente en materias teóricas", "created_at": "2014-07-01 09:30:00",  "updated_at": "2014-07-01 09:00:00"
        }]

### Crear un Instrumento [POST]
+ Request (application/json)

        { "nombre": "Consulta de Laboratorio", "descripcion": "Consulta estudiantil sobre el desempeño docente en materias de Laboratorios Generales" }

+ Response 201 (application/json)

        { "id": 3, "nombre": "Consulta de Laboratorio", "descripcion": "Consulta estudiantil sobre el desempeño docente en materias cde Laboratorios Generales" }

## Instrumento [/instrumentos/{id}]
Un objeto Instrumento en particular con todos sus detalles

+ Parameters
    + id (required, number, `1`) ... `id` numérico del Instrumento. Tiene un valor de ejemplo.

### Obtener un Instrumento [GET]
+ Response 200 (application/json)

    + Header

            X-My-Header: The Value

    + Body

            { "id": 1, "nombre": "Consulta de teórico prácticas", "descripcion": "Consulta estudiantil sobre el desempeño docente en materias teórico-prácticas", "created_at": "2014-07-01 09:00:00",  "updated_at": "2014-07-01 09:00:00" }

### Eliminar un Instrumento [DELETE]
+ Response 204












# Group Bloques
Recursos asociados a los **Bloques** que agrupan **conjuntos de preguntas** de un instrumento

## Colección de Bloques de un Instrumento [/instrumento/{id}/bloques]
### Listar todos los Bloques de un Instrumento [GET]
+ Response 200 (application/json)

        [{
          "id": 1, "nombre": "Sobre el docente", "descripcion": "Aspectos asociados al desempeño del docente", "created_at": "2014-07-01 09:00:00",  "updated_at": "2014-07-01 09:00:00"
        }, {
          "id": 2, "nombre": "Sobre la asignatura", "descripcion": "Aspectos asociados al contenido y planificación de la asignatura", instrumento_id:"1", "created_at": "2014-07-01 09:30:00",  "updated_at": "2014-07-01 09:00:00"
        }]

## Colección de Bloques de un Instrumento [/bloques]
### Crear un Instrumento [POST]
+ Request (application/json)

        { "nombre": "Sobre el laboratorio", "descripcion": "Aspectos asociados a las actividades docentes de laboratorio", instrumento_id:"1" }

+ Response 201 (application/json)

        { "id": 3, "nombre": "Sobre el laboratorio", "descripcion": "Aspectos asociados a las actividades docentes de laboratorio", instrumento: { id:"1", nombre:"Consulta de teórico-prácticas" } }

## Bloques [/bloques/{id}]
Un bloque en particular con todos sus detalles

+ Parameters
    + id (required, number, `1`) ... `id` numérico del Bloque. Tiene un valor de ejemplo.

### Obtener un Instrumento [GET]
+ Response 200 (application/json)

    + Header

            X-My-Header: The Value

    + Body

            { "id": 1, "nombre": "Sobre el docente", "descripcion": "Aspectos asociados al desempeño del docente", instrumento: { id:"1", nombre:"Consulta de teórico-prácticas" }, "created_at": "2014-07-01 09:00:00",  "updated_at": "2014-07-01 09:00:00" }

### Eliminar un Instrumento [DELETE]
+ Response 204


